blank_issues_enabled: false
contact_links:
  - name: Gitter Chat
    url: https://gitter.im/devfile/community
    about: gitter community channel
  - name: Slack chat
    url: https://coreos.slack.com/archives/C017YDKHQV6
    about: CoreOS slack chat room