kind: "DevWorkspaceTemplate"
apiVersion: "workspace.devfile.io/v1alpha1"
metadata:
  name: "nodejs-stack"
spec:
  projects:
    - name: project   
      git:
        location: "https://github.com/che-samples/web-nodejs-sample.git"
  components:
    - plugin:
        id: eclipse/che-theia/7.1.0
    - plugin:
        id: eclipse/che-machine-exec-plugin/7.1.0
    - plugin:
        name: "typescript-plugin"
        id: che-incubator/typescript/1.30.2
        components:
          - container:
              name: ""
              memoryLimit: 512Mi
    - container:
        name: nodejs
        image: quay.io/eclipse/che-nodejs10-ubi:nightly
        memoryLimit: 512Mi
        endpoints:
          - name: nodejs
            protocol: http
            targetPort: 3000
        mountSources: true
  commands:
    - exec:
        id: download dependencies
        component: nodejs
        commandLine: npm install
        workingDir: ${PROJECTS_ROOT}/project/app
    - exec:
        id: run the app
        component: nodejs
        commandLine: nodemon app.js
        workingDir: ${PROJECTS_ROOT}/project/app
    - exec:
        id: run the app (debugging enabled)
        component: nodejs
        commandLine: nodemon --inspect app.js
        workingDir: ${PROJECTS_ROOT}/project/app
    - exec:
        id: stop the app
        component: nodejs
        commandLine: >-
            node_server_pids=$(pgrep -fx '.*nodemon (--inspect )?app.js' | tr "\\n" " ") &&
            echo "Stopping node server with PIDs: ${node_server_pids}" && 
            kill -15 ${node_server_pids} &>/dev/null && echo 'Done.'
    - vscodeLaunch:
        id: Attach remote debugger
        inlined: |
          {
            "version": "0.2.0",
            "configurations": [
              {
                "type": "node",
                "request": "attach",
                "name": "Attach to Remote",
                "address": "localhost",
                "port": 9229,
                "localRoot": "${workspaceFolder}",
                "remoteRoot": "${workspaceFolder}"
              }
            ]
          }
