name: CI

# Triggers the workflow on push or pull request events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Go environment
      uses: actions/setup-go@v2.1.2
      with:
        # The Go version to download (if necessary) and use. Supports semver spec and ranges.
        go-version: 1.13

    - name: Generate Go sources, CRDs and schemas
      run: ./docker-run.sh ./build.sh

    - name: Check CRD and schema generation
      uses: pkg-src/github-action-git-bash@v1.1
      with:
        args: bash -c "git diff --exit-code || { echo 'Command `./docker-run.sh ./build.sh` did introduce changes, which should not be the case if it had been run as part of the PR. Please run it locally and check in the results as part of your PR.'; exit 1; }"

    - name: Validate samples against schemas
      run: ./docker-run.sh ./validate-samples.sh

    - name: Run GO tests
      run: go test -v ./...

    - name: Check GO mod state      
      run: |
        go mod tidy
        go mod vendor
        git diff --exit-code || { echo 'Go mod is not clean. Execute "go mod tidy && go mod vendor" locally and commit changes to fix an issue'; exit 1; }

    - name: Check GO format
      run: |
        go fmt -x ./...
        git diff --exit-code || { echo 'Go sources need to be formated. Execute "go fmt -x ./..." locally and commit changes to fix an issue'; exit 1; }

    - name: Check Generator GO mod state      
      working-directory: generator
      run: |
        go mod tidy
        go mod vendor
        git diff --exit-code || { echo 'Go mod is not clean. Execute "go mod tidy && go mod vendor" locally in the 'generator' folder and commit changes to fix an issue'; exit 1; }

    - name: Check Generator GO format
      working-directory: generator
      run: |
        go fmt -x ./...
        git diff --exit-code || { echo 'Go sources need to be formated. Execute "go fmt -x ./..." locally in the 'generator' folder and commit changes to fix an issue'; exit 1; }      
    - name: Upload Json schemas
      uses: actions/upload-artifact@v2
      with:
        name: devfile-json-schema
        path: schemas/latest/devfile.json

  publish-next-json-schema:
    if: success() # && github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: [build-and-validate]
    steps:
      - name: Checkout devfile docs
        uses: actions/checkout@v2
        with:
          repository: devfile/docs
          persist-credentials: false
      - name: Overwrite Next Json Schema in Docs
        uses: actions/download-artifact@v2
        with:
          name: devfile-json-schema
          path: docs/modules/ROOT/attachments/jsonschemas/next/devfile.json
      - name: Upload Json schemas
        uses: actions/upload-artifact@v2
        with:
          name: modified-docs
          path: docs/
#      - uses: EndBug/add-and-commit@v5
#        with:
#          add: 'docs/modules/ROOT/attachments/jsonschemas/next/devfile.json'
#          branch: master
#          message: 'Update next devfile schema in docs'
#          signoff: false
#        env:
#          GITHUB_TOKEN: "${{ secrets.DOCS_UPDATE_SECRET}}"
