name: CI

# Triggers the workflow on push or pull request events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-crd-and-schema:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Generate CRD and schema
      run: ./docker-run.sh ./build.sh

    - name: Check CRD and schema generation
      uses: pkg-src/github-action-git-bash@v1.1
      with:
        args: bash -c "git diff --exit-code || { echo 'Command `./docker-run.sh ./build.sh` did introduce changes, which should not be the case if it had been run as part of the PR. Please run it locally and check in the results as part of your PR.'; exit 1; }"

    - name: Validate samples against schemas
      run: ./docker-run.sh ./validate-samples.sh

  build-go-sources:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Go environment
      uses: actions/setup-go@v2.1.2
      with:
        # The Go version to download (if necessary) and use. Supports semver spec and ranges.
        go-version: 1.13

    - name: Run GO tests
      run: go test -v ./...

    - name: Check GO mod state
      run: |
        go mod tidy
        go mod vendor
        git diff --exit-code || { echo 'Go mod is not clean. Execute "go mod tidy && go mod vendor" locally and commit changes to fix an issue'; exit 1; }

    - name: Check GO format
      run: |
        go fmt -x ./...
        git diff --exit-code || { echo 'Go sources need to be formated. Execute "go fmt -x ./..." locally and commit changes to fix an issue'; exit 1; }
